services:
  monolithicapp:
    build: fastapi_app
    ports:
      - '13000:8000'
      - '13443:8443'
    volumes:
      #- './fastapi_app:/home/pyuser/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////volume/monolithic.db
    restart: on-failure

  delivery:
    build: services
    ports:
      - '13004:8000'
    volumes:
      - './delivery_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////volume/delivery.db
    restart: on-failure