services:
  order-service:
    build: services/order
    ports:
        - "13001:8000"
    volumes:
        - "./services/order/db_volume:/volume"
    environment:
        PYTHONUNBUFFERED: 1
        SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////volume/orders.db
    restart: on-failure

  delivery:
    build: services/delivery
    ports:
      - '13004:8000'
    volumes:
      - './delivery_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${DELIVERY_DATABASE_URL}
    restart: on-failure

  machineservice:
    build: services/machine
    ports:
      - '13002:8000'
    environment:
      PYTHONUNBUFFERED: 1
    restart: on-failure

  client_service:
    build: services/client
    container_name: client_service
    ports:
      - '13005:8000'
    volumes:
      - './db_volume:/volume'
    environment:
      - PYTHONUNBUFFERED=1
      - SQLALCHEMY_DATABASE_URL=sqlite+aiosqlite:////volume/client.db
    restart: on-failure

  paymentservice:
    build:
      context: services/payment
      dockerfile: Dockerfile
    ports:
      - '13006:8000'
    volumes:
      - './payment_db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////volume/payment.db
      CLIENT_SERVICE_URL: http://clientservice:8000
    restart: on-failure

  haproxy:
    image: haproxy:latest
    ports:
      - "8080:8080"
      - "8404:8404"
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    environment:
      HAPROXY_PORT: 8080
      HAPROXY_STATS_PORT: 8404
    depends_on:
      - order-service
      - delivery
    restart: on-failure
