name: order-service

services:

  order-service:

    build: .

    ports:
      - "13001:8000"

    volumes:
      - "./db_volume:/volume"

    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////volume/orders.db
      CLIENT_SERVICE_URL: ${CLIENT_SERVICE_URL:-http://host.docker.internal:13005}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL:-http://host.docker.internal:13006}
      MACHINE_SERVICE_URL: ${MACHINE_SERVICE_URL:-http://host.docker.internal:13002}
      DELIVERY_SERVICE_URL: ${DELIVERY_SERVICE_URL:-http://host.docker.internal:13004}

    restart: on-failure
